// iTunes Categories
export default [
{ value: "1", title: "Arts" },
{ value: "2", title: "Arts > Design" },
{ value: "3", title: "Arts > Fashion & Beauty" },
{ value: "4", title: "Arts > Food" },
{ value: "5", title: "Arts > Literature" },
{ value: "6", title: "Arts > Performing Arts" },
{ value: "7", title: "Arts > Visual Arts" },
{ value: "8", title: "Business" },
{ value: "9", title: "Business > Business News" },
{ value: "10", title: "Business > Careers" },
{ value: "11", title: "Business > Investing" },
{ value: "12", title: "Business > Management & Marketing" },
{ value: "13", title: "Business > Shopping" },
{ value: "14", title: "Comedy" },
{ value: "15", title: "Education" },
{ value: "16", title: "Education > Education" },
{ value: "17", title: "Education > Education Technology" },
{ value: "18", title: "Education > Higher Education" },
{ value: "19", title: "Education > K-12" },
{ value: "20", title: "Education > Language Courses" },
{ value: "21", title: "Education > Training" },
{ value: "22", title: "Games & Hobbies" },
{ value: "23", title: "Games & Hobbies > Automotive" },
{ value: "24", title: "Games & Hobbies > Aviation" },
{ value: "25", title: "Games & Hobbies > Hobbies" },
{ value: "26", title: "Games & Hobbies > Other Games" },
{ value: "27", title: "Games & Hobbies > Video Games" },
{ value: "28", title: "Government & Organizations" },
{ value: "29", title: "Government & Organizations > Local" },
{ value: "30", title: "Government & Organizations > National" },
{ value: "31", title: "Government & Organizations > Non-Profit" },
{ value: "32", title: "Government & Organizations > Regional" },
{ value: "33", title: "Health" },
{ value: "34", title: "Health > Alternative Health" },
{ value: "35", title: "Health > Fitness & Nutrition" },
{ value: "36", title: "Health > Self-Help" },
{ value: "37", title: "Health > Sexuality" },
{ value: "38", title: "Kids & Family" },
{ value: "39", title: "Music" },
{ value: "40", title: "News & Politics" },
{ value: "41", title: "Religion & Spirituality" },
{ value: "42", title: "Religion & Spirituality > Buddhism" },
{ value: "43", title: "Religion & Spirituality > Christianity" },
{ value: "44", title: "Religion & Spirituality > Hinduism" },
{ value: "45", title: "Religion & Spirituality > Islam" },
{ value: "46", title: "Religion & Spirituality > Judaism" },
{ value: "47", title: "Religion & Spirituality > Other" },
{ value: "48", title: "Religion & Spirituality > Spirituality" },
{ value: "49", title: "Science & Medicine" },
{ value: "50", title: "Science & Medicine > Medicine" },
{ value: "51", title: "Science & Medicine > Natural Sciences" },
{ value: "52", title: "Science & Medicine > Social Sciences" },
{ value: "53", title: "Society & Culture" },
{ value: "54", title: "Society & Culture > History" },
{ value: "55", title: "Society & Culture > Personal Journals" },
{ value: "56", title: "Society & Culture > Philosophy" },
{ value: "57", title: "Society & Culture > Places & Travel" },
{ value: "58", title: "Sports & Recreation" },
{ value: "59", title: "Sports & Recreation > Amateur" },
{ value: "60", title: "Sports & Recreation > College & High School" },
{ value: "61", title: "Sports & Recreation > Outdoor" },
{ value: "62", title: "Sports & Recreation > Professional" },
{ value: "63", title: "Technology" },
{ value: "64", title: "Technology > Gadgets" },
{ value: "65", title: "Technology > Tech News" },
{ value: "66", title: "Technology > Podcasting" },
{ value: "67", title: "Technology > Software How-To" },
{ value: "68", title: "TV & Film" },
]