export default {
    name: 'podcast',
    title: 'Podcast',
    description: 'Create and configure a podcast',
    type: 'document',
    fields: [
        {
            name: 'title',
            type: 'string',
            description: 'A podcast should have a short and catchy title'
        },
        {
            name: 'subtitle',
            type: 'string',
            description: 'That catchy tagline'
        },
        {
            name: 'description',
            type: 'text',
            description: 'What is this podcast about and why should people listen to it?'
        },
        {
            name: 'copyright',
            type: 'string',
            description: 'Who owns the rights to this podcast?'
        },
        {
            name: 'language',
            type: 'string',
            description: 'What language is this podcast in?',
            options: {
                list: [
                    { value: "af", title: "af" },
                    { value: "ar", title: "ar" },
                    { value: "az", title: "az" },
                    { value: "bg", title: "bg" },
                    { value: "bn", title: "bn" },
                    { value: "bs", title: "bs" },
                    { value: "ca", title: "ca" },
                    { value: "cs", title: "cs" },
                    { value: "cy", title: "cy" },
                    { value: "da", title: "da" },
                    { value: "de", title: "de" },
                    { value: "de-at", title: "de-at" },
                    { value: "de-ch", title: "de-ch" },
                    { value: "el", title: "el" },
                    { value: "en", title: "en" },
                    { value: "en-au", title: "en-au" },
                    { value: "en-ca", title: "en-ca" },
                    { value: "en-gb", title: "en-gb" },
                    { value: "en-ie", title: "en-ie" },
                    { value: "en-in", title: "en-in" },
                    { value: "en-nz", title: "en-nz" },
                    { value: "en-us", title: "en-us" },
                    { value: "en-za", title: "en-za" },
                    { value: "eo", title: "eo" },
                    { value: "es", title: "es" },
                    { value: "es-419", title: "es-419" },
                    { value: "es-ar", title: "es-ar" },
                    { value: "es-cl", title: "es-cl" },
                    { value: "es-co", title: "es-co" },
                    { value: "es-cr", title: "es-cr" },
                    { value: "es-ec", title: "es-ec" },
                    { value: "es-mx", title: "es-mx" },
                    { value: "es-pa", title: "es-pa" },
                    { value: "es-pe", title: "es-pe" },
                    { value: "es-us", title: "es-us" },
                    { value: "es-ve", title: "es-ve" },
                    { value: "et", title: "et" },
                    { value: "eu", title: "eu" },
                    { value: "fa", title: "fa" },
                    { value: "fi", title: "fi" },
                    { value: "fr", title: "fr" },
                    { value: "fr-ca", title: "fr-ca" },
                    { value: "fr-ch", title: "fr-ch" },
                    { value: "gl", title: "gl" },
                    { value: "he", title: "he" },
                    { value: "hi", title: "hi" },
                    { value: "hi-in", title: "hi-in" },
                    { value: "hr", title: "hr" },
                    { value: "hu", title: "hu" },
                    { value: "id", title: "id" },
                    { value: "is", title: "is" },
                    { value: "it", title: "it" },
                    { value: "it-ch", title: "it-ch" },
                    { value: "ja", title: "ja" },
                    { value: "km", title: "km" },
                    { value: "kn", title: "kn" },
                    { value: "ko", title: "ko" },
                    { value: "lo", title: "lo" },
                    { value: "lt", title: "lt" },
                    { value: "lv", title: "lv" },
                    { value: "mk", title: "mk" },
                    { value: "mn", title: "mn" },
                    { value: "mr-in", title: "mr-in" },
                    { value: "ms", title: "ms" },
                    { value: "nb", title: "nb" },
                    { value: "ne", title: "ne" },
                    { value: "nl", title: "nl" },
                    { value: "nn", title: "nn" },
                    { value: "or", title: "or" },
                    { value: "pl", title: "pl" },
                    { value: "pt", title: "pt" },
                    { value: "pt-br", title: "pt-br" },
                    { value: "rm", title: "rm" },
                    { value: "ro", title: "ro" },
                    { value: "ru", title: "ru" },
                    { value: "sk", title: "sk" },
                    { value: "sl", title: "sl" },
                    { value: "sr", title: "sr" },
                    { value: "sv", title: "sv" },
                    { value: "sw", title: "sw" },
                    { value: "ta", title: "ta" },
                    { value: "th", title: "th" },
                    { value: "tl", title: "tl" },
                    { value: "tr", title: "tr" },
                    { value: "tt", title: "tt" },
                    { value: "uk", title: "uk" },
                    { value: "ug", title: "ug" },
                    { value: "ur", title: "ur" },
                    { value: "uz", title: "uz" },
                    { value: "vi", title: "vi" },
                    { value: "wo", title: "wo" },
                    { value: "zh-cn", title: "zh-cn" },
                    { value: "zh-hk", title: "zh-hk" },
                    { value: "zh-tw", title: "zh-tw" },
                    { value: "zh-yue", title: "zh-yue" },
                ]
            }
        },
        {
            name: 'explicit',
            type: 'boolean',
            description: 'Do you need to warn parents about the content in this podcast? (You can set this for individual episodes to)'
        },
        {
            name: 'iTunesInfo',
            type: 'object',
            description: 'iTunes has extra stuff',
            fields: [
                {
                    name: 'author',
                    type: 'object',
                    description: 'The name and email of the person or organization that iTunes should list in their different views',
                    fields: [
                        {
                            name: 'email',
                            type: 'email',
                        },
                        {
                            name: 'name',
                            type: 'string'
                        },
                    ]
                },
                {
                    name: 'itunesUrl',
                    type: 'url',
                    description: 'Helpful for when you want to show this podcast in other contexts than iTunes'
                },
                {
                    name: 'type',
                    type: 'string',
                    description: 'Is this a ongoing (episodic) podcast, or is it structured in seasons?',
                    options: {
                        list: [
                            {
                                value: 'episodic',
                                title: 'Episodic',
                            },
                            {
                                value: 'serial',
                                title: 'Serial'
                            }
                        ]
                    }
                },
                {
                    name: 'primaryCategory',
                    title: 'Primary Category',
                    type: 'string',
                    description: 'Where should this podcast be organized in iTunes?',
                    options: {
                        list: [
                            { value: 1, title: "Arts" },
                            { value: 2, title: "Arts &gt; Design" },
                            { value: 3, title: "Arts &gt; Fashion &amp; Beauty" },
                            { value: 4, title: "Arts &gt; Food" },
                            { value: 5, title: "Arts &gt; Literature" },
                            { value: 6, title: "Arts &gt; Performing Arts" },
                            { value: 7, title: "Arts &gt; Visual Arts" },
                            { value: 8, title: "Business" },
                            { value: 9, title: "Business &gt; Business News" },
                            { value: 10, title: "Business &gt; Careers" },
                            { value: 11, title: "Business &gt; Investing" },
                            { value: 12, title: "Business &gt; Management &amp; Marketing" },
                            { value: 13, title: "Business &gt; Shopping" },
                            { value: 14, title: "Comedy" },
                            { value: 15, title: "Education" },
                            { value: 16, title: "Education &gt; Education" },
                            { value: 17, title: "Education &gt; Education Technology" },
                            { value: 18, title: "Education &gt; Higher Education" },
                            { value: 19, title: "Education &gt; K-12" },
                            { value: 20, title: "Education &gt; Language Courses" },
                            { value: 21, title: "Education &gt; Training" },
                            { value: 22, title: "Games &amp; Hobbies" },
                            { value: 23, title: "Games &amp; Hobbies &gt; Automotive" },
                            { value: 24, title: "Games &amp; Hobbies &gt; Aviation" },
                            { value: 25, title: "Games &amp; Hobbies &gt; Hobbies" },
                            { value: 26, title: "Games &amp; Hobbies &gt; Other Games" },
                            { value: 27, title: "Games &amp; Hobbies &gt; Video Games" },
                            { value: 28, title: "Government &amp; Organizations" },
                            { value: 29, title: "Government &amp; Organizations &gt; Local" },
                            { value: 30, title: "Government &amp; Organizations &gt; National" },
                            { value: 31, title: "Government &amp; Organizations &gt; Non-Profit" },
                            { value: 32, title: "Government &amp; Organizations &gt; Regional" },
                            { value: 33, title: "Health" },
                            { value: 34, title: "Health &gt; Alternative Health" },
                            { value: 35, title: "Health &gt; Fitness &amp; Nutrition" },
                            { value: 36, title: "Health &gt; Self-Help" },
                            { value: 37, title: "Health &gt; Sexuality" },
                            { value: 38, title: "Kids &amp; Family" },
                            { value: 39, title: "Music" },
                            { value: 40, title: "News &amp; Politics" },
                            { value: 41, title: "Religion &amp; Spirituality" },
                            { value: 42, title: "Religion &amp; Spirituality &gt; Buddhism" },
                            { value: 43, title: "Religion &amp; Spirituality &gt; Christianity" },
                            { value: 44, title: "Religion &amp; Spirituality &gt; Hinduism" },
                            { value: 45, title: "Religion &amp; Spirituality &gt; Islam" },
                            { value: 46, title: "Religion &amp; Spirituality &gt; Judaism" },
                            { value: 47, title: "Religion &amp; Spirituality &gt; Other" },
                            { value: 48, title: "Religion &amp; Spirituality &gt; Spirituality" },
                            { value: 49, title: "Science &amp; Medicine" },
                            { value: 50, title: "Science &amp; Medicine &gt; Medicine" },
                            { value: 51, title: "Science &amp; Medicine &gt; Natural Sciences" },
                            { value: 52, title: "Science &amp; Medicine &gt; Social Sciences" },
                            { value: 53, title: "Society &amp; Culture" },
                            { value: 54, title: "Society &amp; Culture &gt; History" },
                            { value: 55, title: "Society &amp; Culture &gt; Personal Journals" },
                            { value: 56, title: "Society &amp; Culture &gt; Philosophy" },
                            { value: 57, title: "Society &amp; Culture &gt; Places &amp; Travel" },
                            { value: 58, title: "Sports &amp; Recreation" },
                            { value: 59, title: "Sports &amp; Recreation &gt; Amateur" },
                            { value: 60, title: "Sports &amp; Recreation &gt; College &amp; High School" },
                            { value: 61, title: "Sports &amp; Recreation &gt; Outdoor" },
                            { value: 62, title: "Sports &amp; Recreation &gt; Professional" },
                            { value: 63, title: "Technology" },
                            { value: 64, title: "Technology &gt; Gadgets" },
                            { value: 65, title: "Technology &gt; Tech News" },
                            { value: 66, title: "Technology &gt; Podcasting" },
                            { value: 67, title: "Technology &gt; Software How-To" },
                            { value: 68, title: "TV &amp; Film" },
                        ]
                    }
                }
            ]
        }
    ]
}